---
- hosts: localhost
  vars:
    minecraft_eula_accept: true
    minecraft_max_memory: "{{ (ansible_memtotal_mb * 0.6) | round | int }}m"
    minecraft_initial_memory: "{{ (ansible_memtotal_mb * 0.6) | round | int }}m"
    minecraft_ops: ["w3s7y"]
  tasks:
  - name: Install MC
    import_role:
      name: nolte.minecraft
