---
- hosts: localhost
  vars:
    minecraft_eula_accept: true
    minecraft_max_memory: "{{ ansible_memory_mb.real.total * 0.8 | round | int }}M"
    minecraft_initial_memory: "{{ ansible_memory_mb.real.total * 0.8 | round | int }}M"
    minecraft_ops: ["w3s7y"]
  tasks:
  - name: Install MC
    import_role:
      name: nolte.minecraft
